language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio

env:
- BOARD=esp12e

script:
  - "echo $PWD"
  - "echo $HOME"
  - "ls $PWD"
  - pio lib install https://github.com/jaycollett/ESPBatterySense.git
  - pio lib install "PubSubClient"
  - pio lib install "Adafruit Unified Sensor"
  - pio lib install "DHT sensor library"
  - pio lib install "SerialESP8266wifi"
  - pio lib install "Adafruit DHT Unified"
  - platformio ci --board=$BOARD --lib=$PWD/Arduino\ Code/ESPBatterySense $PWD/Arduino\ Code/ESPBatterySense/ESPBatterySense/ESPBatterySense.ino
  
notifications:
  email:
    on_success: change
    on_failure: change